/* Google Analytics tracking of send email from an "enter" keydown or mousedown event. */
$("#email-submit").on("keydown mousedown", function () {
    if ((event.type === "keydown" && event.which === 13) || event.type === "mousedown") {
        ga('send', 'event', 'email', 'submit');
    }
});

/* Form input tags are generated to allow user-entered fields. */
function getEmailFormFields(tagID) {
    var emailFormFields = '<label>Name<input id="email-name" type="text" /></label><label>Phone<input id="email-phone" type="text" /></label><label>Message<textarea id="email-message" rows="5"></textarea></label>';
    $(emailFormFields).prependTo(tagID);
}

/* Space and tab characters are encoded */
function setWhiteSpace(stringValue) {
    var regExpPattern = /[ \t]/g;
    var newStringValue = stringValue.replace(regExpPattern, "\u00A0");
    return newStringValue;
}

/* Email body is generated by combining the form fields. */
function setEmailBody(tagID) {
    var emailBody = "Name: " + $("#email-name").val() + "\u000APhone: " + $("#email-phone").val() + "\u000AMessage: " + $("#email-message").val();
    emailBody = setWhiteSpace(emailBody);
    $(tagID).val(emailBody);
}

getEmailFormFields("#email-form");

$("#email-submit").on("focus mousedown", function () {
    setEmailBody("#email-body");
});
